version: "3.1"

services:
  enigma-api:
    container_name: enigma_api_${APP_ENV:?error}
    restart: always
    build:
      context: ./enigma-api
    ports:
      - ${API_PORT}:81
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENV}
      - ASPNETCORE_URLS=http://+
      - Cors:Origins=${API_CORS_ORIGINS}
      - ConnectionStrings:MariaDB=Server=enigmadb; Port=3306; Database=enigma; User=${SQL_USER}; Password=${SQL_USER_PASS};
      - Jwt:Issuer=${JWT_ISSUER}
      - Jwt:Audience=${JWT_AUDIENCE}
      - Jwt:Subject=${JWT_SUBJECT}
      - Jwt:Key=${JWT_KEY}
      - Environment=${APP_ENV}
      - Jwt:UiUrl=${APP_UI_BASE_URL}
      - SendInBlue:ApiUri = ${API_SIB_API_URI}
      - SendInBlue:ApiKey = ${API_SIB_API_KEY}
      - SendInBlue:ValidationTemplate:Id = ${API_SIB_TEMPLATE_ID}
      - SendInBlue:ValidationTemplate:AppUrl = ${APP_UI_BASE_URL}
      - Logs:FileRoute = ${API_LOGS_ROUTE}
    depends_on:
      enigmadb:
        condition: service_healthy        

  enigmadb:
    image: mariadb:latest
    container_name: enigma_db_${APP_ENV:?error}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASS}
      MYSQL_DATABASE: enigma
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_USER_PASS}
    volumes:
      - ./.docker/db/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u $$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'  || exit 1"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 120
  enigmaui:
    container_name: enigma_angular_ui_${APP_ENV:?error}
    restart: always
    build:
      context: ./enigma-ui-angular
    ports:
      - ${UI_PORT}:80
    environment:
      - APP_API_BASE_URL=${APP_API_BASE_URL} 