version: "3"

services:
  webapp:
    image: enigmabudgetapi
    container_name: enigma_api
    ports:
      - ${API_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${API_ENV}
      - ASPNETCORE_URLS=http://+
      - Cors:Origins=${CORS_ORIGINS}
      - MariaDB:ConnectionString=${MARIADB_CONNECTIONSTRING}
      - Jwt:Issuer=${JWT_ISSUER}
      - Jwt:Audience=${JWT_AUDIENCE}
      - Jwt:Subject=${JWT_SUBJECT}
      - Jwt:Key=${JWT_KEY}
    depends_on:
      - db
  db:
    image: mariadb
    container_name: enigma_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASS}
      MYSQL_DATABASE: enigma
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_USER_PASS}
    volumes: 
      - ./db/mysql:/var/lib/mysql
    ports:
      - ${SQL_PORT}:3306  
  db_seeder:
    image: mariadb
    container_name: enigma_db_seeder
    environment:
      SQL_DB: enigma
      SQL_USER: ${SQL_USER}
      SQL_USER_PASS: ${SQL_USER_PASS}
      SQL_PORT: ${SQL_PORT}
      SQL_ROOT_PASS: ${SQL_ROOT_PASS}
    command: >
      bash -c "/deploy-script/deploy.sh"
    volumes:
      - ./db/deploy-script:/deploy-script
      - ./db/deploy-sql-scripts:/sql-scripts
    depends_on:
      - db
  nginx:
    image: nginx
    container_name: enigma_angular_ui
    ports:
        - ${UI_PORT}:80
    volumes:
        - ./www/ui:/usr/share/nginx/html