name: Generar Migraciones para entorno

on:
  push:
    branches:
      - testing
      - main
      - release/*
jobs:
  generate-migrations:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: enigma-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    
      - name: Setear Variables de job
        run: |  
           BRANCH_NAME=${GITHUB_REF#refs/heads/}
           TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')
           MIGRATION_NAME="migration_${BRANCH_NAME//\//_}_${TIMESTAMP}"
           echo "MIGRATION_NAME=$MIGRATION_NAME" >> $GITHUB_ENV
           echo "MIGRATION_PROJECT_PATH=EnigmaBudget.Persistence.Contexts.EfCore.Enigma.Migrations.${{secrets.Environment}}/EnigmaBudget.Persistence.Contexts.EfCore.Enigma.Migrations.${{secrets.Environment}}.csproj" >> $GITHUB_ENV
           echo "MIGRATION_CONTEXT=EnigmaBudget.Persistence.Contexts.EfCore.Enigma.EnigmaContext" >> $GITHUB_ENV
           echo "MIGRATION_STARTUP_PROJECT=EnigmaBudget.WebApi/EnigmaBudget.WebApi.csproj" >> $GITHUB_ENV

      - name: Cache NuGet modules
        uses: actions/cache@v3
        env:
          cache-name: cache-nuget-modules
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Instalar EF Tool
        run: |
             dotnet new tool-manifest
             dotnet tool install dotnet-ef

      - name: Restaurar paquetes NuGet
        run: dotnet restore $API_PROJECT_PATH

      - name: Generar migración de EF
        run: |
             dotnet ef migrations add $MIGRATION_NAME --project $MIGRATION_PROJECT_PATH --startup-project $MIGRATION_STARTUP_PROJECT --context $MIGRATION_CONTEXT

      # - name: Hacer commit de las nuevas migraciones
      #   run: |        
      #        git config --local user.email "actions@github.com"
      #        git config --local user.name "GitHub Action"
      #        git add -A
      #        if ! git diff-index --quiet HEAD; then
      #          git commit -m "Actualiza migraciones de base de datos [skip ci]"
      #          git push origin HEAD:${{ github.ref }}
      #        fi